Add switch_root support.
The new script will switch from initramfs to rootfs described in kernel cmdline.
For NFS rootfs, we need to set EXTRA_KERNEL_OPT as follows in bootloader:
setenv -p EXTRA_KERNEL_OPT "root.type=nfs nfs.path=192.168.1.1:/nfsroot rootfstype=initramfs"

For FLASH rootfs, we need to set EXTRA_KERNEL_OPT as follows in bootloader:
setenv -p EXTRA_KERNEL_OPT "root.type=squashfs ubi.mtd=4 root=ubi0_0 rootfstype=initramfs"

Change-Id: Ib63a41533a7a801a972c8da54c2d1e8be607420c

diff --git a/bruno/gfhd100/skel/etc/init.d/S03volcheck b/bruno/gfhd100/skel/etc/init.d/S03volcheck
--- a/bruno/gfhd100/skel/etc/init.d/S03volcheck
+++ b/bruno/gfhd100/skel/etc/init.d/S03volcheck
@@ -3,21 +3,69 @@
 # Volume check service
 #
 
+BOOT_TYPE="release"
+ROOTFS_TYPE="squashfs"
+ROOTFS_MTD_NO=11
+ROOTFS_LOCATION=""
+KERNEL_OPTS=$(cat /proc/cmdline)
+
 check_volume_and_mount () {
   num_vol=`ubinfo --devn=${1} | grep "Volumes count" | awk -F':' '{print $2}'`
   if [[ $num_vol = '0' ]]; then
     ubimkvol /dev/ubi${1} -N ${2} -m
   fi
-  mount -t ubifs ubi${1}:${2} /${2}
+  mount -t ${4} ubi${1}:${2} /${3}
 }
+
+find_rootfs () {
+  for i in ${KERNEL_OPTS};
+  do
+    KERNEL_OPT_TYPE=`echo $i | cut -d'=' -f1`
+    KERNEL_OPT_VAL=`echo $i | cut -d'=' -f2`
+    if [ ${KERNEL_OPT_TYPE} = "root.type" ]; then
+      ROOTFS_TYPE=${KERNEL_OPT_VAL}
+    elif [ ${KERNEL_OPT_TYPE} = "ubi.mtd" ]; then
+      if [ ${KERNEL_OPT_VAL} = "rootfs0" ]; then
+        ROOTFS_MTD_NO=4
+      elif [ ${KERNEL_OPT_VAL} = "rootfs1" ]; then
+        ROOTFS_MTD_NO=5
+      fi
+    elif [ ${KERNEL_OPT_TYPE} = "nfs.path" ]; then
+      ROOTFS_LOCATION=${KERNEL_OPT_VAL}
+    fi
+  done
+}
+
+mount_rootfs() {
+  if [[ ${ROOTFS_TYPE} = "squashfs" ]]; then
+    ROOTFS_LOCATION="/dev/mtdblock$((${ROOTFS_MTD_NO}+7))"
+  elif [[ ${ROOTFS_TYPE} = "nfs" ]]; then
+    mount -t ${ROOTFS_TYPE} ${ROOTFS_LOCATION} /rootfs
+    [[ ! -d /user/rw ]] && mkdir -p /user/rw /rootfs/user/rw
+    [[ ! -d /user/moca ]] && mkdir -p /user/moca /rootfs/user/moca
+    [[ ! -d /user/bsa ]] && mkdir -p /user/bsa /rootfs/user/bsa
+    echo "Skip volume check since rootfs is nfs"
+    exit 0
+  fi
+  if [[ "${ROOTFS_LOCATION}" != "" ]]; then
+    echo "Rootfs found: ${ROOTFS_LOCATION}"
+  else
+    echo "Rootfs not found: ${ROOTFS_LOCATION} ${KERNEL_OPTS}"
+    exit 1
+  fi
+}
+
+find_rootfs
+mount_rootfs
 
 case "$1" in
   start)
     echo -n "Starting volume check: "
-    ubiattach -m 6 -d 0 /dev/ubi_ctrl
-    ubiattach -m 7 -d 1 /dev/ubi_ctrl
-    check_volume_and_mount 0 user
-    check_volume_and_mount 1 config
+    ubiattach -m 6 -d 1 /dev/ubi_ctrl
+    ubiattach -m 7 -d 2 /dev/ubi_ctrl
+    mount -t squashfs ${ROOTFS_LOCATION} /rootfs
+    check_volume_and_mount 1 user user ubifs
+    check_volume_and_mount 2 config config ubifs
     [[ ! -d /user/rw ]] && mkdir -p /user/rw
     [[ ! -d /user/moca ]] && mkdir -p /user/moca
     [[ ! -d /user/bsa ]] && mkdir -p /user/bsa
@@ -28,8 +76,8 @@ case "$1" in
     umount /user
     umount /config
     sleep 1
-    ubidetach -d 0 /dev/ubi_ctrl
     ubidetach -d 1 /dev/ubi_ctrl
+    ubidetach -d 2 /dev/ubi_ctrl
     echo "OK"
     ;;
   restart|reload)
