Recover from the /rw read-only issue.
If the UBIFS failed to recover from LEB scanning, the mounting will fail. The
LEB scanning happens when ubi volume is mounted. So if the mounting fails, we
should try to reformat /user partition to recover from failure.

The mounting failure could cause a lot of programs that running on rw space to fail.

Change-Id: I3f4f0e939debae850845bb20b6a4bcb3edddd150

diff --git a/bruno/gfhd100/skel/etc/init.d/S03volcheck b/bruno/gfhd100/skel/etc/init.d/S03volcheck
--- a/bruno/gfhd100/skel/etc/init.d/S03volcheck
+++ b/bruno/gfhd100/skel/etc/init.d/S03volcheck
@@ -8,18 +8,29 @@ ROOTFS_MTD_NO=9
 ROOTFS_LOCATION=""
 KERNEL_OPTS=$(cat /proc/cmdline)
 
+recover_volume() {
+  ubidetach -m ${1} /dev/ubi_ctrl
+  flash_erase /dev/mtd${1} 0 0
+  ubiattach -m ${1} -d ${2} /dev/ubi_ctrl
+  ubimkvol /dev/ubi${2} -N ${3} -m
+}
+
 check_volume_and_mount () {
   ubiattach -m ${1} -d ${2} /dev/ubi_ctrl
   if [ $? -eq 0 ]; then
     num_vol=$(ubinfo --devn=${2} | python -c "import sys;[sys.stdout.write(l.split(':')[1].strip()) for l in sys.stdin if 'Volumes count' in l]")
     if [ x${num_vol} = x'0' ] || [ x${num_vol} = x ]; then
       echo "No volume associated with mtd${1} (dev:${2}), formatting..."
-      ubidetach -m ${1} /dev/ubi_ctrl
-      flash_eraseall /dev/mtd${1}
-      ubiattach -m ${1} -d ${2} /dev/ubi_ctrl
-      ubimkvol /dev/ubi${2} -N ${3} -m
+      recover_volume ${1} ${2} ${3}
     fi
     mount -t ${5} ubi${2}:${3} /${4}
+    if [ $? -ne 0 ]; then
+      echo "Mounting failed (may due to failed LEB scanning), trying to reformat the partition..."
+      recover_volume ${1} ${2} ${3}
+      mount -t ${5} ubi${2}:${3} /${4}
+      # :TODO: If this mount also fails, need to get TR-069 to indicate back to
+      # the ACS that this box has failed..
+    fi
   else
     echo "Failed to attach mtd${1} to ${2}, formatting..."
     flash_eraseall /dev/mtd${1}
@@ -68,6 +79,9 @@ case "$1" in
   start)
     echo -n "Starting volume check: "
     mount -t squashfs ${ROOTFS_LOCATION} /rootfs
+    if [ $? -ne 0 ]; then
+      echo "Failed to mount rootfs, need to invoke TR-069 download"
+    fi
     check_volume_and_mount 6 1 user user ubifs
     check_volume_and_mount 7 2 config config ubifs
     [ ! -d /user/rw ] && mkdir -p /user/rw
