waveguide: refactor into more files.
waveguide.py was getting too monolithic.  Split some code into more files,
which will make it easier to call it from other new files.  No functionality
changes, except adding gpylint to the 'make test' rules to match catawampus.

Change-Id: Id644c2feb41b0721378feb74103d3aec17a70ecd

diff --git a/waveguide/Makefile b/waveguide/Makefile
--- a/waveguide/Makefile
+++ b/waveguide/Makefile
@@ -2,6 +2,13 @@ INSTALL?=install
 PREFIX=$(DESTDIR)/usr
 BINDIR=$(PREFIX)/bin
 LIBDIR=$(PREFIX)/waveguide
+GPYLINT=$(shell \
+    if which gpylint >/dev/null; then \
+      echo gpylint; \
+    else \
+      echo 'echo "(gpylint-missing)" >&2'; \
+    fi \
+)
 
 all:
 
@@ -15,8 +22,19 @@ runtests: \
 	$(patsubst %_test.py,%.test,$(wildcard *_test.py)) \
 	$(patsubst %_test.sh,%.test,$(wildcard *_test.sh))
 
-test: all
+lint: $(filter-out options.py,$(wildcard *.py))
+	$(GPYLINT) $^
+
+test_only: all
 	./wvtest/wvtestrun $(MAKE) runtests
+
+# Use a submake here, only because otherwise GNU make (3.81) will not print
+# an error about 'test' itself failing if one of the two sub-targets fails.
+# Without such output, 'lint' could fail long before test_only fails, and
+# the test_only output could scroll off the top of the screen, leaving the
+# misleading impression that everything tested successfully.
+test: all
+	$(MAKE) test_only lint
 
 install:
 	mkdir -p $(LIBDIR) $(BINDIR)
